config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_closed', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]

  get "signup", to: "users#new"
  get "signin", to: "sessions#new"
  delete "signout", to: "sessions#destroy"

  resources :places, only: [:index, :show]
  post 'places', to: 'places#search'

  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'

  root "breweries#index"
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :beer_club
  belongs_to :user
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: %i[show edit update destroy]
  before_action :set_beer_clubs, only: %i[new edit create]

  # GET /memberships or /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1 or /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships or /memberships.json
  def create
    @membership = Membership.new(membership_params)
    @membership.user = current_user

    respond_to do |format|
      if @membership.save
        format.html { redirect_to beer_club_url(@membership.beer_club), notice: "#{current_user.username} welcome to #{@membership.beer_club.name}" }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1 or /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to membership_url(@membership), notice: "Membership was successfully updated." }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1 or /memberships/1.json
  def destroy
    membership = @membership
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to current_user, notice: "Membership in #{membership.beer_club.name} ended." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_membership
    @membership = Membership.find(params[:id])
  end

  def set_beer_clubs
    memberships_of_current = current_user.memberships.map(&:beer_club)
    @beer_clubs = BeerClub.where.not(id: memberships_of_current)
  end

  # Only allow a list of trusted parameters through.
  def membership_params
    params.require(:membership).permit(:beer_club_id)
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_with(model: membership) do |form| %>
  <% if membership.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
        <% membership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.select :beer_club_id, options_from_collection_for_select(@beer_clubs, :id, :name), {}, { :class => "form-select" } %>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/memberships/_membership.html.erb
<div id="<%= dom_id membership %>">
  <p>
    <strong>User:</strong>
    <%= membership.user_id %>
  </p>

  <p>
    <strong>Beerclub:</strong>
    <%= membership.beer_club_id %>
  </p>

</div>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Show this membership", @membership %> |
  <%= link_to "Back to memberships", memberships_path %>
</div>

app/views/memberships/index.html.erb
<h1>Memberships</h1>

<div id="memberships">
  <% @memberships.each do |membership| %>
    <%= render membership %>
    <p>
      <%= link_to "Show this membership", membership %>
    </p>
  <% end %>
</div>

<%= link_to "New membership", new_membership_path %>

app/views/memberships/new.html.erb
<h1>Join a club</h1>

<%= render "form", membership: @membership %>

app/views/memberships/show.html.erb
<%= render @membership %>

<div>
  <%= link_to "Edit this membership", edit_membership_path(@membership) %> |
  <%= link_to "Back to memberships", memberships_path %>

  <%= button_to "Destroy this membership", @membership, method: :delete, class:'btn btn-danger' %>
</div>