config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_closed', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]

  get "signup", to: "users#new"
  get "signin", to: "sessions#new"
  delete "signout", to: "sessions#destroy"

  resources :places, only: [:index, :show]
  post 'places', to: 'places#search'

  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'

  root "breweries#index"
end

app/models/beer_club.rb
class BeerClub < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :set_beer_club, only: %i[show edit update destroy]
  before_action :ensure_that_admin, only: [:destroy]

  # GET /beer_clubs or /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all

    order = params[:order] || 'name'

    @beer_clubs = case order
                  when "name" then @beer_clubs.sort_by(&:name)
                  when "founded" then @beer_clubs.sort_by(&:founded).reverse
                  when "city" then @beer_clubs.sort_by(&:city)
                  end
  end

  # GET /beer_clubs/1 or /beer_clubs/1.json
  def show
    @membership = Membership.new
    @membership.beer_club = @beer_club
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs or /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        format.html { redirect_to beer_club_url(@beer_club), notice: "Beer club was successfully created." }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1 or /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to beer_club_url(@beer_club), notice: "Beer club was successfully updated." }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1 or /beer_clubs/1.json
  def destroy
    @beer_club.destroy

    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: "Beer club was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beer_club
    @beer_club = BeerClub.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def beer_club_params
    params.require(:beer_club).permit(:name, :founded, :city)
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_beer_club.html.erb
<div id="<%= dom_id beer_club %>">
  <h2>
    <%= beer_club.name %>
  </h2>

  <p>
    <strong>Founded:</strong>
    <%= beer_club.founded %>
  </p>

  <p>
    <strong>City:</strong>
    <%= beer_club.city %>
  </p>

  <h4>members</h4>

  <% beer_club.members.each do |member| %>
    <p>
      <%= link_to member.username, member %>
    </p>
  <% end %>

</div>

app/views/beer_clubs/_form.html.erb
<%= form_with(model: beer_club) do |form| %>
  <% if beer_club.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
        <% beer_club.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class:"form-label" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :founded, class:"form-label" %>
    <%= form.number_field :founded, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :city, class:"form-label" %>
    <%= form.text_field :city, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Show this beer club", @beer_club %> |
  <%= link_to "Back to beer clubs", beer_clubs_path %>
</div>

app/views/beer_clubs/index.html.erb
<h1>Beer clubs</h1>

<div id="beer_clubs">
  <% if @beer_clubs %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th><%= link_to "Name", beer_clubs_path(order: "name")%></th>
          <th><%= link_to "Founded", beer_clubs_path(order: "founded")%></th>
          <th><%= link_to "City", beer_clubs_path(order: "city")%></th>
        </tr>
      </thead>
      <% @beer_clubs.each do |beer_club| %>
        <tr>
          <td><%= link_to beer_club.name, beer_club_path(beer_club.id) %></td>
          <td><%= beer_club.founded %></td>
          <td><%= beer_club.city %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

<%= link_to "New beer club", new_beer_club_path, class:'btn btn-primary' if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Back to beer clubs", beer_clubs_path %>
</div>

app/views/beer_clubs/show.html.erb
<%= render @beer_club %>

<% if current_user %>
  <% if not @beer_club.members.map { |member| member.username }.include? current_user.username  %>
    <%= form_with(model: @membership) do |form| %>
      <%= form.hidden_field :beer_club_id, value: @beer_club.id %>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <%= form.submit "Join the beer club" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.memberships.find { |membership| membership.beer_club_id == @beer_club.id }, method: :delete) do |form| %>
      <%= form.hidden_field :beer_club_id, value: @beer_club.id %>
      <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.submit "End the membership" %>
<% end %>
  <% end %>

  <div>
    <%= link_to "Edit this beer club", edit_beer_club_path(@beer_club) %> |
    <%= button_to "Destroy this beer club", @beer_club, method: :delete, class:'btn btn-danger' %>
  </div>
<% end %>