config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_closed', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]

  get "signup", to: "users#new"
  get "signin", to: "sessions#new"
  delete "signout", to: "sessions#destroy"

  resources :places, only: [:index, :show]
  post 'places', to: 'places#search'

  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'

  root "breweries#index"
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  include RatingAverage

  validates :name, presence: true
  validates :year, numericality: { greater_than_or_equal_to: 1040,
                                   only_integer: true }
  validate :year_not_greater_than_this_year

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  scope :active, -> { where active: true }
  scope :retired, -> { where active: [nil, false] }

  def year_not_greater_than_this_year
    errors.add(:year, "can't be greater than current year") if year > Time.now.year
  end

  def self.top(n)
    sorted_by_rating_in_desc_order = Brewery.all.sort_by{ |b| -(b.average_rating || 0) }
    sorted_by_rating_in_desc_order.take(n)
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :set_brewery, only: %i[show edit update destroy]
  before_action :ensure_that_admin, only: [:destroy]
  before_action :clear_cache, only: [:create, :update, :destroy]

  # GET /breweries or /breweries.json
  def index
    @breweries = Brewery.all

    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired
  end

  # GET /breweries/1 or /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries or /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to brewery_url(@brewery), notice: "Brewery was successfully created." }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1 or /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to brewery_url(@brewery), notice: "Brewery was successfully updated." }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1 or /breweries/1.json
  def destroy
    @brewery.destroy

    respond_to do |format|
      format.html { redirect_to breweries_url, notice: "Brewery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, !brewery.active

    new_status = brewery.active? ? "active" : "retired"

    redirect_to brewery, notice: "brewery activity status changed to #{new_status}"
  end

  def list
  end

  def clear_cache
    expire_fragment("brewerylist")
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def brewery_params
    params.require(:brewery).permit(:name, :year, :active)
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_brewery.html.erb
<% cache brewery do %>
  <div id="<%= dom_id brewery %>">
    <h2>
      <%= link_to brewery.name, brewery %>
      <% if not brewery.active  %>
        <span class="badge bg-secondary">retired</span>
      <% end %>
    </h2>

    <p>
      Established in <%= brewery.year %>
    </p>

    <p>
      Beers count: <%= brewery.beers.count%>
    </p>

    <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Style</th>
            <th>Rating</th>
          </tr>
        </thead>
        <tbody>
          <% brewery.beers.each do |beer| %>
            <tr>
              <td><%= link_to beer.name, beer %></td>
              <td><%= link_to beer.style.name, beer.style %></td>
              <td><%= round(beer.average_rating) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    <% if brewery.ratings.empty? %>
      brewery has not yet been rated!
    <% else %>
      Brewery has <%= pluralize(brewery.ratings.count, 'rating') %> with an average of <%= round(brewery.average_rating) %>
    <% end %>

  </div>
<% end %>

app/views/breweries/_form.html.erb
<%= form_with(model: brewery) do |form| %>
  <% if brewery.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
        <% brewery.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :active, style: "form-check-label" %>
    <%= form.check_box :active, class:"form-check-input" %>
  </div>

  <div class="mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Show this brewery", @brewery %> |
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/index.html.erb
<h1>Breweries</h1>

<p> Number of active breweries: <%= @active_breweries.count %> </p>

<% cache "brewerylist", skip_digest: true do %>
  <div id="active_breweries">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Founded</th>
          <th>Beers</th>
          <th>Rating</th>
        </tr>
      </thead>
      <tbody>
        <% @active_breweries.each do |brewery| %>
          <tr>
            <td><%= link_to brewery.name, brewery %></td>
            <td><%= brewery.year %></td>
            <td><%= brewery.beers.count %></td>
            <td><%= round(brewery.average_rating) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<%= link_to("New brewery", new_brewery_path, class: "btn btn-primary") if current_user %>

app/views/breweries/list.html.erb
<h2>Breweries</h2>

<table id="brewerytable" class="table table-hover">
  <thead>
    <tr>
      <th> <span id="name">Name</span> </th>
      <th> <span id="year">Year</span> </th>
      <th> <span id="beercount">Beer count</span> </th>
      <th> <span id="active">Active</span> </th>
    </tr>
  <thead>
  <tbody>
    <div id="brewerylist"></div>
  </tbody>
</table>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/show.html.erb
<%= render @brewery %>

<div>
  <%= link_to "Change activity", toggle_activity_brewery_path(@brewery.id), data: {turbo_method: "post"}, class: "btn btn-primary" %>
  <%= link_to "Edit this brewery", edit_brewery_path(@brewery), class:'btn btn-primary' if current_user %>
  <%= button_to "Destroy this brewery", @brewery, method: :delete, class:'btn btn-danger' if current_user %>
</div>

<%= link_to "Back to breweries", breweries_path %>